version: 0.2

env:
  variables:
    NODE_OPTIONS: '--openssl-legacy-provider'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies using Node.js 18
      - npm install
      - npm install react-scripts --save
      - npm install -g yarn

  pre_build:
    commands:
      - echo Installing dependencies
      - yarn

  build:
    commands:
      - echo Building the React project
      - yarn build

artifacts:
  files:
    - build/**/*
  base-directory: build
  discard-paths: yes