version: 0.2
phases:
  install:
    commands:
      - echo installing Node.js 18
      - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
      - echo installing Yarn
      - curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - yum install -y yarn
  pre_build:
    commands:
      - echo installing dependencies
      - yarn install
  build:
    commands:
      - echo building project
      - yarn build
artifacts:
  files:
    - "**/*"
  base-directory: build
